chrome.runtime.onMessage.addListener(function (request) {
    switch (request.menuItemId) {
        case "simplify-with-GPT":
            simplify(request.selectionText);
        default:
            console.log(`Menu Item ${request.menuItemId} not recognized`)
    }
});

function simplify(selectionText) {
    let selectedRange = grabSelecedRange();
    if (selectedRange == null) {
        console.log("There was an issue with grabbing the selected element")
    }
    simplifyTextWithGPT(selectedRange, selectionText);

}

function grabSelecedRange() {
    if (window.getSelection) {
        var sel = window.getSelection();
        if (sel.rangeCount) {
            range = sel.getRangeAt(0);
            return range
        }
    }
}

function replaceSelectedText(range, replacementText) {
    /**
     * Grabs the currently selected text and replaces
     * it with whatever in inputed.
     * Note: it does not use the selectionText generated by
     * the contextMenu
     * 
     * @since 0.0.1
     * 
     * @param 
     * @param {string} replacementText Text to be replaced.
     */
    range.deleteContents();
    range.insertNode(document.createTextNode(replacementText));
}
