chrome.runtime.onMessage.addListener(function (request) {
    switch (request.menuItemId) {
        case "simplify-with-GPT":
            simplify(request.selectionText);
            break;
        default:
            console.log(`Menu Item ${request.menuItemId} not recognized`)
    }
});

function simplify(selectionText) {
    simplifyTextWithGPT(selectionText)
    replaceSelectedText("test")
}

function replaceSelectedText(replacementText) {
    /**
     * Grabs the currently selected text and replaces
     * it with whatever in inputed.
     * Note: it does not use the selectionText generated by
     * the contextMenu
     * 
     * @since 0.0.1
     * 
     * @param {string} replacementText Text to be replaced.
     */
    var sel, range;
    if (window.getSelection) {
        sel = window.getSelection();
        if (sel.rangeCount) {
            range = sel.getRangeAt(0);
            range.deleteContents();
            range.insertNode(document.createTextNode(replacementText));
        }
    } else if (document.selection && document.selection.createRange) {
        range = document.selection.createRange();
        range.text = replacementText;
    }
}
